# Generated by Django 4.2.7 on 2023-11-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_video_rename_category_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='archivo',
            field=models.FileField(default='default_video.mp4', upload_to='videos/'),
        ),
    ]
