# Generated by Django 4.2.7 on 2023-11-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_caption_video_titulo_remove_video_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='archivo',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
